# Generated by Django 3.2.22 on 2023-12-19 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video',
            new_name='video_pc',
        ),
        migrations.AddField(
            model_name='post',
            name='video_mobile',
            field=models.FileField(null=True, upload_to='intruder_image/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
